# BackupFlow Configuration

s3:
  endpoint: "play.minio.local:9000"
  secure: true
  accessKey: "ACCESS_KEY"
  secretKey: "SECRET_KEY"
  bucket: "backups"
  rootDir: "FlowStack/BackupFlow"

backup:
  include:
    # Use '*' in worlds list (or leave all include fields empty) to auto-detect all worlds (folders containing level.dat)
    # If ALL of: worlds list empty, extraPaths empty, and plugins/configs not explicitly set -> implicit '*'
    worlds: ["world", "world_nether", "world_the_end"]  # or ["*"] for auto-detect
    plugins: true      # omit AND use '*' to auto include
    configs: true      # omit AND use '*' to auto include
    extraPaths: []     # additional relative paths; '*' here is ignored
  compression: zip   # zip | gz (tar.gz) | none
  chunkSizeMB: 32    # reserved for future incremental diff logic
  retention:
    enableLifecycle: false   # if true rely on bucket lifecycle rules
    maxLocalEntries: 10      # how many local manifest records to keep
  hardTimeoutSeconds: 600    # watchdog hard timeout for a single full backup (0=disable)
  phaseStaleSeconds: 300     # warn if a phase (e.g., COLLECT) exceeds this without progress (0=disable)
  skipUnchanged: true        # skip backup if no files changed since last backup (based on content hash)
  schedule:
    enabled: true
    intervalMinutes: 60     # run every X minutes
    jitterSeconds: 30       # random jitter to avoid sync storms in clusters

restore:
  allowDirectDownload: true
  tempDir: "plugins/BackupFlow/work/tmp"
  restoreDir: "restores"

manifest:
  storeInBucket: true
  prefix: "manifests"  # stored under rootDir/manifests/<name>.json

integrity:
  hashes: true   # if true include per-file SHA-256 hashes in manifest for verification

logging:
  verbose: false

metrics:
  enabled: true

# List existing backups at startup (counts only)
autoListOnStart: true

# Toggle colored prefix output (set false for plain logs/console)
color:
  enabled: true

# Cache backup timestamp list for tab completion (seconds, 0=disable cache)
timestampCacheSeconds: 60
