name: BackupFlow
main: com.c4g7.backupflow.BackupFlowPlugin
version: ${project.version}
author: c4g7-dev
description: Cloud-native incremental backup manager using S3/MinIO
api-version: '1.20'
commands:
  BackupFlow:
    description: BackupFlow root command
    usage: /<command> help
    aliases: [bf]
permissions:
  backupflow.admin:
    description: All BackupFlow permissions
    default: op
  backupflow.backup:
    description: Run manual backups
    default: op
  backupflow.restore:
    description: Restore backups (any section)
    default: op
  backupflow.verify:
    description: Verify backup integrity via hashes
    default: op
  backupflow.retention:
    description: View retention plans
    default: op
  backupflow.list:
    description: List backup timestamps
    default: true
  backupflow.manifests:
    description: List manifests
    default: true
  backupflow.version:
    description: View plugin version
    default: true
  backupflow.status:
    description: View backup status and metrics
    default: true
  backupflow.reload:
    description: Reload BackupFlow configuration
    default: op
