name: Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -DskipTests package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BackupFlow-jar
          path: target/BackupFlow-*-all.jar
      - name: Create Release (tag build)
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          BODY_FILE="/tmp/release_body.md"
          if [ -f CHANGELOG.md ]; then
            awk -v tag="${TAG#v}" 'BEGIN{capture=0} \
              /^## \[/ { \
                if(capture){exit} \
                if($0 ~ "^## \\"[" tag "\\""){capture=1; print $0; next} \
              } \
              { if(capture) print }' CHANGELOG.md > "$BODY_FILE"
          fi
          if [ ! -s "$BODY_FILE" ]; then
            echo "BackupFlow $TAG" > "$BODY_FILE"
            echo "\n(CHANGELOG section not found or empty)" >> "$BODY_FILE"
          fi
          gh release create "$TAG" target/BackupFlow-*-all.jar \
            --title "BackupFlow $TAG" \
            --notes-file "$BODY_FILE" --verify-tag
